### ISSUE TITLE
Override scaffolded setting issue

### ISSUE THREAD

**Issue by BilalDja** [strongloop/loopback-component-explorer#173]
Hi, _if this issue is solved please refer to the solution_.
I'm trying to override the explorer default settings by creating a second file name as : **component-config.local.json**. I suppose that this file has priority higher then **component-config.json**. When I set the "loopback-component-explorer" to null the app breaks, and this is the stacktrace:
C:\Users\appFolder\node_modules\loopback-boot\lib\config-loader.js:257
  var origValue = target[key];
                        ^

### TypeError: Cannot read property 'mountPath' of null
    at mergeSingleItemOrProperty (C:\Users\Bilal\projects\siyara-backend\node_modules\loopback-boot\lib\config-loader.js:257:25)
    at mergeObjects (C:\Users\Bilal\projects\siyara-backend\node_modules\loopback-boot\lib\config-loader.js:250:15)
    at mergeSingleItemOrProperty (C:\Users\Bilal\projects\siyara-backend\node_modules\loopback-boot\lib\config-loader.js:270:12)
    at mergeObjects (C:\Users\Bilal\projects\siyara-backend\node_modules\loopback-boot\lib\config-loader.js:250:15)
    at mergeComponentConfig (C:\Users\Bilal\projects\siyara-backend\node_modules\loopback-boot\lib\config-loader.js:241:13)
    at mergeConfigurations (C:\Users\Bilal\projects\siyara-backend\node_modules\loopback-boot\lib\config-loader.js:142:5)
    at loadNamed (C:\Users\Bilal\projects\siyara-backend\node_modules\loopback-boot\lib\config-loader.js:76:16)
    at Object.ConfigLoader.loadComponents (C:\Users\Bilal\projects\siyara-backend\node_modules\loopback-boot\lib\config-loader.js:56:10)
    at compile (C:\Users\Bilal\projects\siyara-backend\node_modules\loopback-boot\lib\compiler.js:60:20)
    at bootLoopBackApp (C:\Users\Bilal\projects\siyara-backend\node_modules\loopback-boot\index.js:139:22)

**Comment by clinm** [comment]
Hello BilalDja,

I know I'm late for your issue but I just ran into it myself. I've found a way around by just making my files as following : 

```````
// component-config.json
{
// empty here !
}

// component-config.development.json
{
  "loopback-component-explorer": {
    "mountPath": "/explorer"
  }
}
``````

**Comment by gunjpan** [comment]
@BilalDja : Yes, `component-config.local.json` has higher priority than `component-config.json`.

I'm curious what you're trying to achieve by setting up `explorerPath` to `null`? are you trying to disable `explorer` for `local` setup?
If that's the case, you can [disable the `explorer`](https://docs.strongloop.com/display/APIC/Environment-specific+configuration#Environment-specificconfiguration-DisablingAPIExplorer) as following:

**component-config.local.json**

```javascript
{
  "loopback-component-explorer": null
}
```

Closing this as resolved for now. If you need further assistance, please comment here and I'll be happy to assist you. Thank you.

**Comment by gentunian** [comment]
It's weird how it works. Modifying `component-config.json` to be:

```
{
  "loopback-component-explorer": null
}
```

Won't allow you set `loopback-component-explorer` in another file. It's like it is not about priority but order. I mean, `component-config.json` is parsed even you have `component-config.development.json`.

That will explain this behaviour:
```
node_modules/loopback-boot/lib/config-loader.js:264
  var origValue = target[key];
                        ^

TypeError: Cannot read property 'mountPath' of null
    at mergeSingleItemOrProperty (node_modules/loopback-boot/lib/config-loader.js:264:25)
    at mergeObjects (node_modules/loopback-boot/lib/config-loader.js:257:15)
    at mergeSingleItemOrProperty (node_modules/loopback-boot/lib/config-loader.js:277:12)
    at mergeObjects (node_modules/loopback-boot/lib/config-loader.js:257:15)
    at mergeSingleItemOrProperty (node_modules/loopback-boot/lib/config-loader.js:277:12)
    at mergeObjects (node_modules/loopback-boot/lib/config-loader.js:257:15)
    at mergeComponentConfig (node_modules/loopback-boot/lib/config-loader.js:248:13)
    at mergeConfigurations (node_modules/loopback-boot/lib/config-loader.js:149:5)
    at loadNamed (node_modules/loopback-boot/lib/config-loader.js:82:16)
    at Object.ConfigLoader.loadComponents (node_modules/loopback-boot/lib/config-loader.js:62:10)
    at compile (node_modules/loopback-boot/lib/compiler.js:80:20)
    at bootLoopBackApp (node_modules/loopback-boot/index.js:153:22)
    at Object.<anonymous> (server/server.js:24:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

```

When you have `component-config.json`:

```
{
  "loopback-component-explorer": null
}
```

and `component-config.development.json`:

```
{
  "loopback-component-explorer": {
    "mountPath": "/explorer"
  }
}
```

It seems what is happening is that the key "loopback-component-explorer" is being set to null when parsing `component-config.json`, and then, when parsing `component-config.development.json` the key is null and you can't set "mountPath" there.

Why should I disable explorer in `component-config.json` ? Because by default my convention is to be production. Clean every file to be productive. Why? because I wan't to keep my structure and content simple. If you need something for developing, then add what you need. I think it's better than having a lot of environment files around your code.
